#! /bin/sh

if [ "$1" == "stop" ]; then
	echo "Nothing to stop"
	exit 0
fi

BOOT_DEV=/dev/mmcblk0p1

if ! grep -q "$BOOT_DEV" "/proc/mounts" ; then
	mount -o ro "$BOOT_DEV" /boot
fi

if -r "/tmp/boot/hostname" ; then
	hostname "$(cat /boot/hostname)"
else
	hostname audio-"`ifconfig eth0 | grep HWaddr | sed -e 's/.*HWaddr //' | tr -d :`"
fi
