#! /bin/sh

case "$1" in
    start)
	printf "Loading modules"
	modprobe snd_bcm2835
	hostname audio-"`ifconfig eth0 | grep HWaddr | sed -e 's/.*HWaddr //' | tr -d :`"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Not stoping"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
