#! /bin/sh
# Build configuration files and start a shairport sync for each sound card

# Additional options that are passed to Shairport Sync
OPTIONS="-d"

if [ "$1" == "stop" ]; then
        exec killall shairport-sync
fi
if [ "$1" == "restart" ]; then
        killall shairport-sync
fi

# make sure the modules are loaded
echo "Loading modules"
modprobe snd_bcm2835
modprobe snd-usb-audio

for card in /sys/class/sound/card* ; do
        num="$(echo $card | sed 's/^.*[^0-9]\([0-9]*\)$/\1/')"
	port="$(expr 7000 + $num)"
	config="/tmp/shairport-sync.$num.conf"

	# find the USB port that this audio card is plugged into
	dev="$(readlink $card)"
	if echo "$dev" | grep -q platform/soc ; then
		# this is the builtin hardware sound devi
		id=0
		echo "$card: Builtin audio"
	elif echo "$dev" | grep -q usb ; then
		# this is a usb, with up to four slots
		#id="$(echo $dev | sed 's/.*\/[0-9]-[0-9]\.\([0-9]\):1.0\/sound\/card.*/\1/')"
		id="$(echo $dev | sed 's/.*\/\([^/]*\):1.0\/sound\/card.*/\1/')"
		echo "$card: USB port $id"
	else
		# this is unknown, give it a generic name
		id="card$num"
	fi

	# see if there is a file on the boot partition that names
	# this channel
	if [ -r "/boot/name.$id" ] ; then
		name="$(cat /boot/name.$id)"
		echo "$card: $name ($id)"
	else
		name="audio-$id"
		echo "$card: No friendly name"
	fi
	
	cat > "$config" <<EOF
general =
{
        name = "$name";
        output_backend = "alsa";
	port = $port;
	airplay_device_id_offset = $num;
};

alsa =
{
        output_device = "default:$num";
};

mqtt =
{
	enabled = "yes";
	hostname = "dashboard";
	topic = "audio/$name";
	publish_parsed = "yes";
	publish_cover = "no";
	enable_remote = "yes";
};
EOF

        echo "Start shairport-sync.$num: $name"
        #start-stop-daemon -S -q --exec
        /usr/bin/shairport-sync \
                --justDaemoniseNoPIDFile \
		--configfile "$config" \

        sleep 1
done

